#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 005 - Fix Galactic Chart Grid Dimensions (8×8 → 16×8)

set -e

echo "========================================"
echo "Star Raiders Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js and npm found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

cd /Users/moog/Documents/Star-Raiders

if [ ! -d "node_modules" ]; then
    npm install
else
    echo "node_modules already exists, skipping install"
fi

# ============================================
# START DEV SERVER
# ============================================

echo ""
echo "Starting development server..."

npm run dev &
DEV_PID=$!

wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Game: http://localhost:5173"
echo ""
echo "To view the Galactic Chart:"
echo "  1. Open http://localhost:5173 in your browser"
echo "  2. Select difficulty and start game"
echo "  3. Press 'G' to open Galactic Chart"
echo ""
echo "Press Ctrl+C to stop the development server"
echo ""

# Keep script running
wait $DEV_PID
