#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Dual Photon Cannon Weapon System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Star Raiders - Dual Photon Cannon Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/moog/Documents/Star-Raiders"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

echo ""
echo "Checking dependencies..."

if [ ! -d "$PROJECT_DIR/node_modules" ]; then
    echo "Installing npm dependencies..."
    cd "$PROJECT_DIR" && npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START VITE DEV SERVER
# ============================================

echo ""
echo "Starting Vite development server..."

cd "$PROJECT_DIR" && npm run dev &
DEV_PID=$!

wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Game:     http://localhost:5173"
echo ""
echo "Controls:"
echo "  F - Front View"
echo "  A - Aft View"
echo "  G - Galactic Chart"
echo "  L - Long Range Scan"
echo "  Space - Fire Photon Cannons"
echo "  0-9 - Engine Speed"
echo ""
echo "Development:"
echo "  PID: $DEV_PID"
echo "  To stop: kill $DEV_PID"
echo ""
echo "Files to modify:"
echo "  src/entities/PhotonTorpedo.ts"
echo "  src/game/Game.ts"
echo ""
