#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Star Raiders - Enemy Weapon Firing System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${CYAN}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max} seconds${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready!${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Checking dependencies...${NC}"

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js first.${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed. Please install npm first.${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js: $(node -v)${NC}"
echo -e "${GREEN}npm: $(npm -v)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing dependencies...${NC}"

cd /Users/moog/Documents/Star-Raiders
npm install

# ============================================
# START DEV SERVER
# ============================================

echo ""
echo -e "${YELLOW}Starting development server...${NC}"

npm run dev &
DEV_PID=$!

wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  ${CYAN}Game:${NC} http://localhost:5173"
echo ""
echo "Development Commands:"
echo "  npm run dev    - Start development server"
echo "  npm run build  - Build for production"
echo "  npx tsc --noEmit - Type check without emitting"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

# Keep script running
wait $DEV_PID
